### ISSUE TITLE
Add health check to My Appliances page

### ISSUE THREAD

**Issue by machristie** [galaxyproject/cloudlaunch-ui#18]
Utilize the new health check task ([added as part of the multi-task refactoring](https://github.com/galaxyproject/cloudlaunch/pull/85)) to show a live status for all appliances for which CloudLaunch has the user's credentials.

# UI Changes
* split the current My Appliances list into two <s>tabs</s> pages, **Current Instances** and **Launch History**
* The appliances that are listed under **Current Instances** are all appliances for which 
  * (Edit 9/14) The appliance has not been deleted explicitly by the user
  * (Edit 9/14: <s>CloudLaunch has stored credentials for that appliance's cloud</s>)
  * (Edit 9/14: <s>CloudLaunch has in memory temporary credentials for that appliance's cloud</s>)
* All appliance launches are listed under **Launch History**
* The columns displayed under **Current Instances** are the following:
  * App icon
  * Deployment name and other details
  * Status
    * Instance status is one of [the InstanceState enum values](https://github.com/gvlproject/cloudbridge/blob/gce/cloudbridge/cloud/interfaces/resources.py#L376)
    * When health check task is running this column should display a busy indicator to show that the current status is being updated
    * (Edit 9/14) If credentials aren't available, status icon is "broken cloud link"
  * Application URL or IP Address
  * Actions - this is a new column that will have a **Refresh Status** button and a **Delete** button for clouds where saved credentials exist
* The columns displayed under **Launch History** are the following:
  * App icon
  * Deployment name and other details
  * *(In the future we might have an Actions column here too with a Re-launch buttton)*
* After launching an application the user will always go to the **Current Instances** <s>tab</s> page. (Edit 9/14: <s>However, if the application was launched with temporary credentials the application will be displayed in the **Launch History** <s>tab</s> page the next time the user visits CloudLaunch.</s>)
  * applications are always displayed under **Current Instances** until the user explicitly removes them by clicking on **Delete**.  Applications can be archived or terminated and archived, see notes on what happens when **Delete** button is clicked below for more info.
* Clicking the **Refresh Status** button will trigger an asynchronous health status check task
* Clicking the **Delete** button will cause a modal to appear asking the user if they want to just remove the application from the **Current Instances** list or if they also want to actually terminate and delete the instance

# Other considerations
* We decided to not do a background refresh of health check at this time
* Automatically refresh status when the user goes to My Appliances page? Perhaps only for instances that haven't had a health check task run in the past 24 hours.
  * (Edit 9/14) Decided yes to automatically update instances that haven't had a health check task run in the past 10 minutes

**Comment by afgane** [comment]
> split the current My Appliances list into two tabs, Current Instances and Launch History

Did we not agree on going with two separate pages vs. tabs, linked from the masthead dropdown menu?

**Comment by machristie** [comment]
@afgane I honestly couldn't remember but I had "two tabs" in my notes from the meeting. I'm fine with either way, with a slight preference for separate pages.

**Comment by afgane** [comment]
I'm leaning toward the two pages as well.

**Comment by machristie** [comment]
@afgane This [change of the DeploymentTaskSerializer result from type DictField to type CharField](https://github.com/machristie/cloudlaunch/commit/089e2466f0fcbad3214d575d4e65ef8de589326a#diff-434da2ecc65c9ff2ee2db6fd77c81f4f) is causing me an issue. The problem is that the serialized `result` value is a string, but it isn't proper JSON either.  An example value of `result` in the serialized response is
```
"{'instance_status': 'terminated'}"
```
I tried to do a `JSON.parse` but  it doesn't parse because it is using single quote instead of double quote.

Is it okay to change `result` back to a DictField?  I think the only problem is [when the database result value is not JSON](https://github.com/machristie/cloudlaunch/blob/dev/django-cloudlaunch/baselaunch/models.py#L360) but maybe we can deal with that by returning `{"result": self._result}` (or something to make it a dict) in that case?

**Comment by afgane** [comment]
Given the `"{'instance_status': 'terminated'}"` is just a return string, have you tried just flipping the quotes and seeing if it works?

I wanted to keep the `DictField` in the database, but was not able to because of the type issue described here: https://github.com/machristie/cloudlaunch/commit/089e2466f0fcbad3214d575d4e65ef8de589326a#diff-df9f9c31795954c14533b82f186d10f2R337
