### ISSUE TITLE
npm ERR! Failed at the cloudlaunch-ui@0.1.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/cloudlaunch-ui#2]
Hey :),

I wanted to get started on the UI. Unfortunately, I have this error on `npm start`

```
npm ERR! Failed at the cloudlaunch-ui@0.1.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
npm ERR! This is most likely a problem with the cloudlaunch-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite"
```

But looking into `npm bugs cloudlaunch-ui`, I have this:

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/remi/.nvm/versions/node/v4.4.4/bin/node" "/Users/remi/.nvm/versions/node/v4.4.4/bin/npm" "bugs" "cloudlaunch-ui"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code E404

npm ERR! 404 Not Found: cloudlaunch-ui
npm ERR! 404
npm ERR! 404 'cloudlaunch-ui' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/remi/Google_Drive/Dev/cloudlaunch-ui/npm-debug.log
```

What do you think I should do to fix this?

**Comment by nuwang** [comment]
Just finished up with the workshop. If you're around, we can get together and try to debug this.

**Comment by remimarenco** [comment]
Just finished too on Ansible workshop. Are you at library?

**Comment by remimarenco** [comment]
So, just for informations purpose, the issue comes from `tsconfig.json`. It seems it works, at least on my machine (OS X El Captain), by changing `"target": "es6"` to `"target": "es5"`

(@dannon)

**Comment by nuwang** [comment]
@remimarenco If you pull in the latest changes, it should be possible to login to the client with a local django account again. You may also need to make a copy of settings_local.py from the sample and make sure DEBUG=True in there and hopefully, everything should work fine.

**Comment by remimarenco** [comment]
Thanks @nuwang, but it did not work unfortunately :/.

**Comment by nuwang** [comment]
@remimarenco @afgane 
I guess this is ok now. If you encounter any local compilation issues with the latest checkout, try deleting the typings folder.
