### ISSUE TITLE
Fetch CloudMan clusters does not refresh on credentials change

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch-ui#23]
If a user progresses to the step 2 of the launch wizard for the CloudMan appliance and fetches existing cluster but then goes back to the first step to change credentials, the previously fetched list is still available instead of the fetch button showing up again.

**Comment by nuwang** [comment]
Fixed in https://github.com/galaxyproject/cloudlaunch-ui/commit/04faca6bb038724d53bb177a2f0d59810fe28290
